# إعدادات مشروع التعرف على الكلام

data:
  raw_data_path: "data/raw"
  processed_data_path: "data/processed"
  transcripts_path: "data/transcripts/transcripts.txt"

training:
  epochs: 10
  batch_size: 16
  learning_rate: 0.001

model:
  input_dim: 40
  hidden_dim: 128
  output_dim: 30  # عدد الحروف أو الرموز المستخدمة
